var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,g){c!=Array.prototype&&c!=Object.prototype&&(c[e]=g.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var e=0;return $jscomp.iteratorPrototype(function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var e=c[Symbol.iterator];return e?e.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var e,g=[];!(e=c.next()).done;)g.push(e.value);return g};$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
module.exports=function(){function c(e,g,h,n){this.message=e;this.expected=g;this.found=h;this.location=n;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,c)}(function(c,g){function e(){this.constructor=c}e.prototype=g.prototype;c.prototype=new e})(c,Error);c.buildMessage=function(c,g){function e(c){return c.charCodeAt(0).toString(16).toUpperCase()}function n(c){return c.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,
"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(c){return"\\x0"+e(c)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(c){return"\\x"+e(c)})}function p(c){return c.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(c){return"\\x0"+e(c)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(c){return"\\x"+e(c)})}var t={literal:function(c){return'"'+n(c.text)+
'"'},"class":function(c){var e="",d;for(d=0;d<c.parts.length;d++)e+=c.parts[d]instanceof Array?p(c.parts[d][0])+"-"+p(c.parts[d][1]):p(c.parts[d]);return"["+(c.inverted?"^":"")+e+"]"},any:function(c){return"any character"},end:function(c){return"end of input"},other:function(c){return c.description}};return"Expected "+function(c){var e=Array(c.length),d;for(d=0;d<c.length;d++){var g=d;var h=c[d];h=t[h.type](h);e[g]=h}e.sort();if(0<e.length){for(c=d=1;d<e.length;d++)e[d-1]!==e[d]&&(e[c]=e[d],c++);
e.length=c}switch(e.length){case 1:return e[0];case 2:return e[0]+" or "+e[1];default:return e.slice(0,-1).join(", ")+", or "+e[e.length-1]}}(c)+" but "+(g?'"'+n(g)+'"':"end of input")+" found."};return{SyntaxError:c,parse:function(e,g){function h(b,a){return{type:"literal",text:b,ignoreCase:a}}function n(b,a,c){return{type:"class",parts:b,inverted:a,ignoreCase:c}}function p(b){return{type:"other",description:b}}function t(b){var a=u[b],c;if(!a){for(c=b-1;!u[c];)c--;a=u[c];for(a={line:a.line,column:a.column};c<
b;)10===e.charCodeAt(c)?(a.line++,a.column=1):a.column++,c++;u[b]=a}return a}function x(b,a){var c=t(b),e=t(a);return{start:{offset:b,line:c.line,column:c.column},end:{offset:a,line:e.line,column:e.column}}}function y(b){l<k||(l>k&&(k=l,v=[]),v.push(b))}function d(b){var a=Array(b.length),c;for(c=0;c<b.length;c++)a[c]=b.charCodeAt(c)-32;return a}function z(b){b=B[b];for(var a=0,c=[],d=b.length,g=[],f=[],h,k;;){for(;a<d;)switch(b[a]){case 0:f.push(m[b[a+1]]);a+=2;break;case 1:f.push(void 0);a++;break;
case 2:f.push(null);a++;break;case 3:f.push(q);a++;break;case 4:f.push([]);a++;break;case 5:f.push(l);a++;break;case 6:f.pop();a++;break;case 7:l=f.pop();a++;break;case 8:f.length-=b[a+1];a+=2;break;case 9:f.splice(-2,1);a++;break;case 10:f[f.length-2].push(f.pop());a++;break;case 11:f.push(f.splice(f.length-b[a+1],b[a+1]));a+=2;break;case 12:f.push(e.substring(f.pop(),l));a++;break;case 13:g.push(d);c.push(a+3+b[a+1]+b[a+2]);f[f.length-1]?(d=a+3+b[a+1],a+=3):(d=a+3+b[a+1]+b[a+2],a+=3+b[a+1]);break;
case 14:g.push(d);c.push(a+3+b[a+1]+b[a+2]);f[f.length-1]===q?(d=a+3+b[a+1],a+=3):(d=a+3+b[a+1]+b[a+2],a+=3+b[a+1]);break;case 15:g.push(d);c.push(a+3+b[a+1]+b[a+2]);f[f.length-1]!==q?(d=a+3+b[a+1],a+=3):(d=a+3+b[a+1]+b[a+2],a+=3+b[a+1]);break;case 16:f[f.length-1]!==q?(g.push(d),c.push(a),d=a+2+b[a+1],a+=2):a+=2+b[a+1];break;case 17:g.push(d);c.push(a+3+b[a+1]+b[a+2]);e.length>l?(d=a+3+b[a+1],a+=3):(d=a+3+b[a+1]+b[a+2],a+=3+b[a+1]);break;case 18:g.push(d);c.push(a+4+b[a+2]+b[a+3]);e.substr(l,m[b[a+
1]].length)===m[b[a+1]]?(d=a+4+b[a+2],a+=4):(d=a+4+b[a+2]+b[a+3],a+=4+b[a+2]);break;case 19:g.push(d);c.push(a+4+b[a+2]+b[a+3]);e.substr(l,m[b[a+1]].length).toLowerCase()===m[b[a+1]]?(d=a+4+b[a+2],a+=4):(d=a+4+b[a+2]+b[a+3],a+=4+b[a+2]);break;case 20:g.push(d);c.push(a+4+b[a+2]+b[a+3]);m[b[a+1]].test(e.charAt(l))?(d=a+4+b[a+2],a+=4):(d=a+4+b[a+2]+b[a+3],a+=4+b[a+2]);break;case 21:f.push(e.substr(l,b[a+1]));l+=b[a+1];a+=2;break;case 22:f.push(m[b[a+1]]);l+=m[b[a+1]].length;a+=2;break;case 23:f.push(q);
0===w&&y(m[b[a+1]]);a+=2;break;case 24:a+=2;break;case 25:a++;break;case 26:h=b.slice(a+4,a+4+b[a+3]);for(k=0;k<b[a+3];k++)h[k]=f[f.length-1-h[k]];f.splice(f.length-b[a+2],b[a+2],m[b[a+1]].apply(null,h));a+=4+b[a+3];break;case 27:f.push(z(b[a+1]));a+=2;break;case 28:w++;a++;break;case 29:w--;a++;break;default:throw Error("Invalid opcode: "+b[a]+".");}if(0<g.length)d=g.pop(),a=c.pop();else break}return f[0]}g=void 0!==g?g:{};var q={},r={root:0},A=0,m=[function(b){return{type:"block",statements:b}},
function(b,a){return{type:"statement",attributes:b,items:a}},"@",h("@",!1),function(b,a){return{type:"attribute",name:b,val:a}},function(b,a){return a},function(b,a){return[].concat([b],$jscomp.arrayFromIterable(a))},function(b){return b},function(b){return b},function(b,a,c){return{type:"item",identifier:b,args:a,block:c}},function(b){return b},",",h(",",!1),":",h(":",!1),function(b){return b},function(b,a){return{type:"itemArg",tag:b,value:a}},p("string"),'"',h('"',!1),function(b){return{type:"string",
value:b.join("")}},/^[^"]/,n(['"'],!0,!1),function(b){return b.join("")},p("namespaced identifier"),"::",h("::",!1),function(b,a){return{type:"identifier",ident:[b,a.ident].filter(function(a){return void 0!=a}).join("::")}},p("identifier"),/^[0-9a-zA-Z_]/,n([["0","9"],["a","z"],["A","Z"],"_"],!1,!1),function(b){return b},"=>",h("=>",!1),"(",h("(",!1),")",h(")",!1),"{",h("{",!1),"}",h("}",!1),p("semicolon"),";",h(";",!1),p("whitespace"),/^[ \t]/,n([" ","\t"],!1,!1),/^[\n\r]/,n(["\n","\r"],!1,!1),"\n",
h("\n",!1),"\r\n",h("\r\n",!1)],B=[d('%;6/8#$;!0#*;!&/($8": "! )("\'#&\'#'),d('%$;"0#*;"&/;#;#/2$;5/)$8#:!#""!)(#\'#("\'#&\'#'),d('%2"""6"7#/D#;./;$;#/2$;6/)$8$:$$""!)($\'#(#\'#("\'#&\'#'),d("%;$/}#$%;//;#;6/2$;#/)$8#:%#\"% )(#'#(\"'#&'#0E*%;//;#;6/2$;#/)$8#:%#\"% )(#'#(\"'#&'#&/)$8\":&\"\"! )(\"'#&'#"),d("%;*/' 8!:'!! )./ &%;%/' 8!:(!! )"),d('%;./F#;&." &"/8$;)." &"/*$8#:)##"! )(#\'#("\'#&\'#'),d("%;0/C#;'/:$;1/1$;6/($8$:*$!\")($'#(#'#(\"'#&'#"),d('%;(/\u0089#$%2+""6+7,/;#;6/2$;(/)$8#:%#"% )(#\'#("\'#&\'#0K*%2+""6+7,/;#;6/2$;(/)$8#:%#"% )(#\'#("\'#&\'#&/)$8":&""! )("\'#&\'#'),
d('%%;./7#2-""6-7./($8":/"!!)("\'#&\'#." &"/D#;6/;$;$/2$;6/)$8$:0$"#!)($\'#(#\'#("\'#&\'#'),d("%;2/J#$;!0#*;!&/:$;3/1$;6/($8$: $!\")($'#(#'#(\"'#&'#"),d('<%22""6273/G#$;+0#*;+&/7$22""6273/($8#:4#!!)(#\'#("\'#&\'#=." 71'),d('%$45""5!76/,#0)*45""5!76&&&#/\' 8!:7!! )'),d("<%;-/' 8!:(!! )=.\" 78"),d('%29""697:." &"/;#;./2$;-/)$8#:;#"! )(#\'#("\'#&\'#.# &;6'),d('<%29""697:." &"/Z#%$4=""5!7>/,#0)*4=""5!7>&&&#/"!&,)/1$;6/($8#:?#!!)(#\'#("\'#&\'#=." 7<'),d('%2@""6@7A/,#;6/#$+")("\'#&\'#'),d('%2B""6B7C/,#;6/#$+")("\'#&\'#'),
d('%2D""6D7E/,#;6/#$+")("\'#&\'#'),d('%2F""6F7G/,#;6/#$+")("\'#&\'#'),d('%2H""6H7I/,#;6/#$+")("\'#&\'#'),d('%2+""6+7,/,#;6/#$+")("\'#&\'#'),d('<%2K""6K7L/,#;6/#$+")("\'#&\'#=." 7J'),d('<$;7.# &;90)*;7.# &;9&=." 7M'),d('4N""5!7O'),d('4P""5!7Q'),d('2R""6R7S.) &2T""6T7U')],l=0,u=[{line:1,column:1}],k=0,v=[],w=0;if("startRule"in g){if(!(g.startRule in r))throw Error("Can't start parsing from rule \""+g.startRule+'".');A=r[g.startRule]}r=z(A);if(r!==q&&l===e.length)return r;r!==q&&l<e.length&&y({type:"end"});
throw function(b,a,d){return new c(c.buildMessage(b,a),b,a,d)}(v,k<e.length?e.charAt(k):null,k<e.length?x(k,k+1):x(k,k));}}}();